version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:5173"
    networks:
      - todonet

  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "8000:8000"
    networks:
      - todonet
    depends_on:
      - mongo
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
      placement:
        constraints: [node.role == worker]

  mongo:
    image: mongo:5
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - todonet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - todonet

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - todonet

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - todonet

volumes:
  mongo_data:

networks:
  todonet:
    driver: bridge